name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest


    # Step to set up the SSH agent
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    # Separate step to SSH into EC2 and run the Docker container
    - name: SSH to EC2 and run Docker
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@54.161.109.115 "sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest && sudo docker run -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest"
